version: "3.9"
services:
  builder-perl:
    build: .
    image: "rodagurto/perl534:alpine"
    container_name: alpine_perl534
    stdin_open: true # docker run -i
    tty: true        # docker run -t